[package]
name = "ruffle_wstr"
version = "0.1.0"
edition = "2021"
authors = ["Arthur Heuillard <arthur.heuillard<orange.fr>"]
license = "MIT OR Apache-2.0"

[dependencies]
gc-arena = { git = "https://github.com/ruffle-rs/gc-arena" }
