[package]
name = "swf"
version = "0.1.0"
authors = ["Mike Welsh"]
repository = "https://github.com/Herschel/swf-rs.git"
homepage = "https://github.com/Herschel/swf-rs.git"
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "Read and write the Adobe Flash SWF file format."

[dependencies]
clippy = {version = "*", optional = true}
byteorder = "1.0"
flate2 = "1.0"
num-derive = "0.2"
num-traits = "0.2"
xz2 = {version = "0.1.5", optional = true}

[features]
default = []
lzma-support = ["xz2"]