[package]
name = "swf"
version = "0.1.0"
authors = ["Mike Welsh"]
repository = "https://github.com/Herschel/swf-rs.git"
homepage = "https://github.com/Herschel/swf-rs.git"
license = "GPLv3"
readme = "README.md"
description = "Read and write the Adobe Flash SWF file format."

[dependencies]
byteorder = "*"
enum_primitive = "*"
flate2 = "*"
num = "*"
xz2 = { git = "https://github.com/alexcrichton/xz2-rs", rev = "09ce8db2" }