[package]
name = "swf"
version = "0.1.0"
authors = ["Mike Welsh"]
repository = "https://github.com/Herschel/swf-rs.git"
homepage = "https://github.com/Herschel/swf-rs.git"
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "Read and write the Adobe Flash SWF file format."

[dependencies]
byteorder = "1.0"
enum_primitive = "0.1.1"
flate2 = "0.2.17"
num = "0.1"
xz2 = { git = "https://github.com/alexcrichton/xz2-rs", rev = "09ce8db2" }