[package]
name = "swf"
version = "0.1.1"
edition = "2018"
authors = ["Mike Welsh"]
repository = "https://github.com/Herschel/swf-rs.git"
homepage = "https://github.com/Herschel/swf-rs.git"
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "Read and write the Adobe Flash SWF file format."

[dependencies]
byteorder = "1.0"
num-derive = "0.2"
num-traits = "0.2"
libflate = {version = "0.1", optional = true}
flate2 = {version = "1.0", optional = true}
xz2 = {version = "0.1.5", optional = true}

[features]
default = ["libflate"]
lzma-support = ["xz2"]