[package]
name = "ruffle_render_wgpu"
version = "0.1.0"
authors = ["Nathan Adams <dinnerbone@dinnerbone.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
image = { version = "0.23.14", default-features = false }
log = "0.4"
ruffle_core = { path = "../../core" }
ruffle_render_common_tess = { path = "../common_tess" }
futures = "0.3.17"
bytemuck = { version = "1.7.0", features = ["derive"] }
raw-window-handle = "0.3.3"
clap = { version = "3.0.0-beta.5", optional = true }
enum-map = "1.1.1"

# wgpu desktop
[target.'cfg(not(target_arch = "wasm32"))'.dependencies.wgpu]
version = "0.11"
features = ["spirv"]

# wgpu wasm
[target.'cfg(target_arch = "wasm32")'.dependencies.wgpu]
version = "0.11"
features = ["spirv-web"]

[features]
render_debug_labels = []
render_trace = ["wgpu/trace"]
