[package]
name = "ruffle_render_wgpu"
version = "0.1.0"
authors = ["Nathan Adams <dinnerbone@dinnerbone.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs", rev = "6cfd4243603b495fed568445792feed51e78aac2" }
image = "0.23.12"
jpeg-decoder = "0.1.20"
log = "0.4"
lyon = "0.17.1"
ruffle_core = { path = "../../core" }
futures = "0.3.9"
bytemuck = "1.4.1"
raw-window-handle = "0.3.3"
clap = { version = "3.0.0-beta.2", optional = true }
enum-map = "0.6.3"

[features]
render_debug_labels = []
render_trace = ["wgpu/trace"]
