[package]
name = "ruffle_render_wgpu"
version = "0.1.0"
authors = ["Nathan Adams <dinnerbone@dinnerbone.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
wgpu = "0.6"
wgpu-native = "0.5"
image = "0.23.10"
jpeg-decoder = "0.1.20"
log = "0.4"
lyon = "0.16.2"
ruffle_core = { path = "../../core" }
futures = "0.3.6"
bytemuck = "1.4.1"
raw-window-handle = "0.3.3"
clap = { version = "3.0.0-beta.2", optional = true }

[features]
render_debug_labels = []
