version: 2.1
description: Ruffle - Flash Player emulator written in Rust

jobs:
  build:
    docker:
      - image: circleci/rust:1.37
    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Tests
          command: |
            rustup toolchain install stable
            rustup run stable rustc --version --verbose
            rustup run stable cargo test --package=ruffle_core
      - run:
          name: Clippy + Format
          command: |
            sudo apt-get update
            sudo apt-get -y install libasound2-dev # Required for cpal crate on Linux
            rustup toolchain install stable
            rustup component add --toolchain stable clippy
            rustup run stable cargo clippy --version
            rustup run stable cargo clippy --all --tests -- -D warnings
            rustup component add --toolchain stable rustfmt
            rustup run stable cargo fmt --version
            rustup run stable cargo fmt --all -- --check
      - run:
          name: Desktop Build
          command: |
            sudo apt-get update
            sudo apt-get -y install libasound2-dev # Required for cpal crate on Linux
            rustup toolchain install stable
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            rustup run stable cargo build --package ruffle_desktop
      - run:
          name: Web Build
          command: |
            curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
            sudo apt-get install -y nodejs
            rustup toolchain install stable
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            cd web/demo
            npm install
            npm run build
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"