[package]
name = "ruffle_render_canvas"
version = "0.1.0"
authors = ["Ruffle LLC <ruffle@ruffle.rs>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
base64 = "0.13.0"
fnv = "1.0.7"
js-sys = "0.3.57"
log = "0.4"
ruffle_web_common = { path = "../../web/common" }
svg = "0.10.0"
percent-encoding = "2.1.0"
png = "0.17.5"
wasm-bindgen = "=0.2.80"

[dependencies.jpeg-decoder]
version = "0.2.6"
default-features = false # can't use rayon on web

[dependencies.ruffle_core]
path = "../../core"
default-features = false

[dependencies.web-sys]
version = "0.3.57"
features = [
    "CanvasGradient", "CanvasPattern", "CanvasRenderingContext2d", "CanvasWindingRule", "CssStyleDeclaration",
    "Document", "DomMatrix", "Element", "HtmlCanvasElement", "HtmlImageElement", "ImageData", "Navigator", "Path2d",
    "SvgMatrix", "SvgsvgElement",
]
