[package]
name = "fluster_core"
version = "0.1.0"
authors = ["Mike Welsh <mwelsh@gmail.com>"]
edition = "2018"

[dependencies]
bacon_rajan_cc = "0.2"
generational-arena = "0.1"
log = "0.4"
rand = "0.6.5"
swf = { git = "https://github.com/Herschel/swf-rs", version = "*" }

