[package]
name = "ruffle_core"
version = "0.1.0"
authors = ["Mike Welsh <mwelsh@gmail.com>"]
edition = "2018"

[dependencies]
bitstream-io = "0.8.2"
fnv = "1.0.3"
gc-arena = "0.1.1"
gc-arena-derive = "0.1.1"
generational-arena = "0.2.2"
libflate = "0.1.26"
log = "0.4"
minimp3 = { version = "0.3.3", optional = true }
puremp3 = { version = "0.1", optional = true }
rand = "0.6.5"
swf = { path = "../swf" }
enumset = "0.4.2"
smallvec = "0.6.10"

[dependencies.jpeg-decoder]
version = "0.1.16"
default-features = false # can't use rayon on web

[dev-dependencies]
approx = "0.3.2"

[features]
default = ["minimp3"]
lzma = ["swf/lzma"]
