[package]
name = "ruffle_render"
version = "0.1.0"
authors = ["Ruffle LLC <ruffle@ruffle.rs>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
swf = {path = "../swf"}
gc-arena = { git = "https://github.com/ruffle-rs/gc-arena" }
log = "0.4"
gif = "0.11.4"
png = { version = "0.17.5" }
flate2 = "1.0.24"
smallvec = { version = "1.9.0", features = ["union"] }
downcast-rs = "1.2.0"
lyon = { version = "1.0.0", optional = true }

[dependencies.jpeg-decoder]
version = "0.2.6"
default-features = false # can't use rayon on web

[dev-dependencies]
approx = "0.5.1"

[features]
default = []
tessellator = ["lyon"]