[package]
name = "ruffle_web_common"
version = "0.1.0"
authors = ["Ruffle LLC <ruffle@ruffle.rs>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
js-sys = "0.3.58"
log = "0.4"
wasm-bindgen = "=0.2.81"

[dependencies.web-sys]
version = "0.3.58"
features = ["Window"]
