[package]
name = "ruffle_web_common"
version = "0.1.0"
authors = ["Mike Welsh <mwelsh@gmail.com>"]
edition = "2018"

[dependencies]
js-sys = "0.3.25"
log = "0.4"
wasm-bindgen = "0.2.57"

[dependencies.web-sys]
version = "0.3.34"
features = ["Window"]