[package]
name = "ruffle_macros"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[lib]
proc-macro = true

[dependencies]
quote = "1.0.21"
syn = { version = "1.0.105", features = ["full"] }
