[package]
name = "build_playerglobal"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
convert_case = "0.6.0"
proc-macro2 = "1.0.49"
quote = "1.0.21"
swf = { path = "../../swf" }
clap = {version = "4.0.27", features = ["derive"]}
serde = {version = "1.0.150", features = ["derive"]}
serde-xml-rs = "0.6.0"
colored = "2.0.0"
