name: Test Web

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Test node ${{ matrix.node_version }} / rust ${{ matrix.rust_version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.rust_version == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        # We most likely don't care about rust versions here, we'll catch those issues in "test rust"
        node_version: ['10', '12']
        rust_version: ['stable']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: Use stable rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust_version }}

    - name: Install linux depencencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get -y install libasound2-dev 

    - name: Install wasm-pack
      run: cargo install wasm-pack

    - name: Install web
      working-directory: web
      run: |
        npm ci

    - name: Install web/core
      working-directory: web/packages/core
      run: |
        npm ci

    - name: Build web
      working-directory: web
      run: |
        npm run bootstrap
        npx eslint .
        npm run build
        npm run test
