[package]
name = "ruffle_web"
version = "0.1.0"
authors = ["Mike Welsh <mwelsh@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Web (WASM) bindings to the Ruffle flash player"
readme = "README.md"
homepage = "https://ruffle.rs"
repository = "https://github.com/ruffle-rs/ruffle/"
publish = false # This crate is useless alone, people should use the npm package

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["canvas", "console_error_panic_hook", "console_log", "webgl"]
lzma = ["ruffle_core/lzma"]
avm_debug = ["ruffle_core/avm_debug"]
canvas = ["ruffle_render_canvas"]
webgl = ["ruffle_render_webgl"]

[dependencies]
byteorder = "1.3.4"
console_error_panic_hook = { version = "0.1.1", optional = true }
console_log = { version = "0.2", optional = true }
fnv = "1.0.7"
generational-arena = "0.2.8"
js-sys = "0.3.45"
log = "0.4"
ruffle_render_canvas = { path = "../render/canvas", optional = true }
ruffle_web_common = { path = "common" }
ruffle_render_webgl = { path = "../render/webgl", optional = true }
url = "2.1.1"
wasm-bindgen = "0.2.65"
wasm-bindgen-futures = "0.4.17"
chrono = { version = "0.4", features = ["wasmbind"] }

[dependencies.ruffle_core]
path = "../core"
default-features = false
features = ["puremp3"]

[dependencies.web-sys]
version = "0.3.44"
features = [
    "AddEventListenerOptions", "AudioBuffer", "AudioBufferSourceNode", "AudioParam", "AudioProcessingEvent", "AudioContext", "AudioDestinationNode",
    "AudioNode", "CanvasRenderingContext2d", "ChannelMergerNode", "ChannelSplitterNode", "CssStyleDeclaration", "Document",
    "Element", "Event", "EventTarget", "GainNode", "HtmlCanvasElement", "HtmlElement", "HtmlImageElement", "MouseEvent",
    "Navigator", "Node", "Performance", "PointerEvent", "ScriptProcessorNode", "UiEvent", "Window", "Location", "HtmlFormElement",
    "KeyboardEvent", "Path2d", "CanvasGradient", "CanvasPattern", "SvgMatrix", "SvgsvgElement", "Response", "Request", "RequestInit",
    "Blob", "BlobPropertyBag", "Storage", "WheelEvent"]

[dev-dependencies]
wasm-bindgen-test = "0.3.17"
