[package]
name = "ruffle_web"
version = "0.1.0"
authors = ["Mike Welsh <mwelsh@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["canvas", "console_error_panic_hook", "console_log", "webgl"]
lzma = ["ruffle_core/lzma"]
canvas = ["ruffle_render_canvas"]
webgl = ["ruffle_render_webgl"]

[dependencies]
byteorder = "1.3.4"
console_error_panic_hook = { version = "0.1.1", optional = true }
console_log = { version = "0.2", optional = true }
fnv = "1.0.7"
generational-arena = "0.2.8"
js-sys = "0.3.25"
log = "0.4"
ruffle_render_canvas = { path = "../render/canvas", optional = true }
ruffle_web_common = { path = "common" }
ruffle_render_webgl = { path = "../render/webgl", optional = true }
url = "2.1.1"
wasm-bindgen = "0.2.57"
wasm-bindgen-futures = "0.4.4"

[dependencies.ruffle_core]
path = "../core"
default-features = false
features = ["puremp3"]

[dependencies.web-sys]
version = "0.3.34"
features = [
    "AudioBuffer", "AudioBufferSourceNode", "AudioParam", "AudioProcessingEvent", "AudioContext", "AudioDestinationNode",
    "AudioNode", "CanvasRenderingContext2d", "ChannelMergerNode", "ChannelSplitterNode", "CssStyleDeclaration", "Document",
    "Element", "Event", "EventTarget", "GainNode", "HtmlCanvasElement", "HtmlElement", "HtmlImageElement", "MouseEvent",
    "Navigator", "Node", "Performance", "PointerEvent", "ScriptProcessorNode", "UiEvent", "Window", "Location", "HtmlFormElement",
    "KeyboardEvent", "Path2d", "CanvasGradient", "CanvasPattern", "SvgMatrix", "SvgsvgElement", "Response", "Request", "RequestInit",
    "Blob", "BlobPropertyBag"]

[dev-dependencies]
wasm-bindgen-test = "0.3.7"
