[package]
name = "ruffle_web"
version = "0.1.0"
authors = ["Mike Welsh <mwelsh@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook", "console_log"]

[dependencies]
base64 = "0.11.0"
byteorder = "1.3.1"
console_error_panic_hook = { version = "0.1.1", optional = true }
console_log = { version = "0.1", optional = true }
fnv = "1.0.3"
generational-arena = "0.2.2"
js-sys = "0.3.25"
log = "0.4"
png = "0.15.2"
svg = "0.6.0"
url = "1.7.2"
wasm-bindgen = "0.2.48"

[dependencies.jpeg-decoder]
version = "0.1.18"
default-features = false # can't use rayon on web

[dependencies.ruffle_core]
path = "../core"
default-features = false
features = ["puremp3"]

[dependencies.web-sys]
version = "0.3.33"
features = [
    "AudioBuffer", "AudioBufferSourceNode", "AudioParam", "AudioProcessingEvent", "AudioContext", "AudioDestinationNode", 
    "AudioNode", "CanvasRenderingContext2d", "ChannelMergerNode", "ChannelSplitterNode", "CssStyleDeclaration", "Document",
    "Element", "Event", "EventTarget", "GainNode", "HtmlCanvasElement", "HtmlElement", "HtmlImageElement", "MouseEvent",
    "Navigator", "Node", "Performance", "PointerEvent", "ScriptProcessorNode", "UiEvent", "Window", "Location", "HtmlFormElement",
    "KeyboardEvent"]

[dev-dependencies]
wasm-bindgen-test = "0.3.6"
