[package]
name = "fluster_web"
version = "0.1.0"
authors = ["Mike Welsh <mwelsh@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook", "console_log"]

[dependencies]
console_error_panic_hook = { version = "0.1.1", optional = true }
console_log = { version = "0.1", optional = true }
fluster_core = { path = "../core" }
js-sys = "0.3.19"
wasm-bindgen = "0.2"

[dependencies.web-sys]
version = "0.3.19"
features = ["CanvasRenderingContext2d", "CssStyleDeclaration", "HtmlCanvasElement", "HtmlElement"]

[dev-dependencies]
wasm-bindgen-test = "0.2"