[package]
name = "ruffle_desktop"
version = "0.1.0"
authors = ["Mike Welsh <mwelsh@gmail.com>"]
edition = "2018"
default-run = "ruffle_desktop"

[dependencies]
cpal = "0.10.0"
ruffle_core = { path = "../core" }
glium = "0.26.0-alpha5"
glutin = "0.22.0-alpha5"
env_logger = "0.6.1"
generational-arena = "0.2.2"
image = "0.21.1"
jpeg-decoder = "0.1.16"
log = "0.4"
lyon = "0.13.3"
sample = "0.10.0"
structopt = "0.2.15"
winit = "0.20.0-alpha4"
webbrowser = "0.5.2"
url = "2.1.0"
