[package]
name = "fluster_desktop"
version = "0.1.0"
authors = ["Mike Welsh <mwelsh@gmail.com>"]
edition = "2018"

[dependencies]
fluster_core = { path = "../core" }
glutin = "0.20"
env_logger = "0.6.1"
structopt = "0.2.15"